name: Unit Testing

on:
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest
          
      - name: Merge to master on success
        if: ${{ success() }}
        run: |
          git config --global user.email "faizanjavid71@gmail.com"
          git config --global user.name "ItsFaizan71"
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.sha }}
          git push origin main
